Add wildcard matching in resource counters
uwiger/gproc pull request #128
Opened 2016-11-30 21:48 UTC by uwiger

From the edoc

* `rc` - 'resource counter', tracks the number of resource properties
   with the same name. When the resource count reaches `0`, any triggers
   specified using an `on_zero` attribute may be executed (see below).
   If `Name` is a tuple, the last element of the name can contain a
  wildcard, using the symbol `'\\_'`. This will make the resource
   counter keep track of any resources where all elements match except
   the last position. For example, `{rc,l,{a,b,'\\_'}}` would keep
   track of both `{r,l,{a,b,1}}` and `{r,l,{a,b,2}}`.

2020-09-17 12:11 UTC, tolbrino requested changes

2020-09-17 12:11 UTC, tolbrino commented on src/gproc.erl
> +%%    pattern (se below) for a resource property is not allowed.
```suggestion
%%    pattern (see below) for a resource property is not allowed.
```

2020-09-17 12:11 UTC, tolbrino commented on src/gproc.erl
> +%% TODO: We don't call valid_key/1 here, since
why?

2020-09-17 12:11 UTC, tolbrino commented on src/gproc_lib.erl
> +	 valid_opts/2,
```suggestion
	   valid_opts/2,
```

2020-09-17 13:05 UTC, uwiger commented on src/gproc.erl
> +%% TODO: We don't call valid_key/1 here, since
Sorry, a remnant from earlier.

2020-09-17 13:07 UTC, uwiger commented on src/gproc.erl
> +%% TODO: We don't call valid_key/1 here, since
```suggestion
```

2020-09-18 07:12 UTC, merged

2020-09-18 07:15 UTC, tolbrino commented
LGTM